Paths:
  path_to_data: C:\Users\Stephen.Cole\Dropbox\My PC (XT-LPT-012)\Documents\Core Consultants\Internal Dashboard\Data\ECommerceDatasets
  path_to_log: C:\Users\Stephen.Cole\Dropbox\My PC (XT-LPT-012)\Documents\Core Consultants\Internal Dashboard\Python\log
Files:
  input_csv: 
    - olist_customers_dataset.csv
    - olist_geolocation_dataset.csv
    - olist_order_items_dataset.csv
    - olist_order_payments_dataset.csv
    - olist_order_reviews_dataset.csv
    - olist_orders_dataset.csv
    - olist_products_dataset.csv
    - olist_sellers_dataset.csv
    - product_category_name_translation.csv
  extra_csv:
    - state_codes_dataset.csv
  output_csv: olist_modelling_dataset_CLEAN.csv
